[package]
name = "sbor"
version = "0.4.0"
edition = "2021"

[dependencies]
sbor-derive = { path = "../sbor-derive" }
hashbrown = { version = "0.12", optional = true }
serde = { version = "1.0", default-features = false, optional = true }
hex = { version = "0.4.3", default-features = false, optional = true }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["serde?/std", "hex?/std"]
alloc = ["hashbrown", "serde?/alloc", "hex?/alloc"]

# Enable serde derives for SBOR value and type models
serde = ["serde/derive", "hex/serde"]

# Enable tracing
trace = ["sbor-derive/trace"]
